name: STRT TRBL Music Inc.
favicon: null
layout_spectrum: 0.760444013401866
typography_spectrum: 0.6971459984779358
title: The home of STRT TRBl Music.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#321610'
    - '#ffffff'
    - '#e4654a'
    - '#e1dddc'
    - '#948682'
  brandStrength: 0.875
  lightness: 0.2187079202849418
  saturation: 0.43179767834953964
  rhythmicContrast: 0.2917946202214807
purpose: []
